# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_ur_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: position_controllers/GripperActionController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    right_hand_controller:
      type: position_controllers/GripperActionController

    mount_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    mount_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


left_ur_manipulator_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
left_gripper_controller:
  ros__parameters:
    joint: left_robotiq_85_left_knuckle_joint

right_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7

right_hand_controller:
  ros__parameters:
    joint: right_panda_finger_joint1

mount_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - mount_panda_joint1
      - mount_panda_joint2
      - mount_panda_joint3
      - mount_panda_joint4
      - mount_panda_joint5
      - mount_panda_joint6
      - mount_panda_joint7

mount_hand_controller:
  ros__parameters:
    joint: mount_panda_finger_joint1